name: Deploy to production server
on:
  push:
    branches:
      - master
    tags:
      - '**-prod**'

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest

    steps:
      - name: Start Notification
        uses: appleboy/telegram-action@master
        with:
          to: ${{ secrets.MN_TG_CHAT_ID }}
          token: ${{ secrets.TG_BOT_TOKEN }}
          format: markdown
          message: |
            *♻️ Деплой запущен*
            *🌍 Сервер:* Мечта
            *📱 Приложение:* «Logger Old Node»
            *🛠️ Тип:* Backend

      - name: Git clone repository
        uses: actions/checkout@v4

      - name: Create BZIP deployment package
        run: tar -cjf logger-old-node.tar.bz2 ./*

      - name: Copy file to serve
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          port: ${{ secrets.PORT }}
          source: logger-old-node.tar.bz2
          target: ~/uploads/

      - name: Deploy
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          port: ${{ secrets.PORT }}
          script: |
            if [ -d "/var/www/${{ secrets.BACKEND_FOLDER }}" ]; then
              cd /var/www/${{ secrets.BACKEND_FOLDER }}

              # Удаляет все кроме папки node_modules
              ls | grep -v "node_modules" | xargs rm -rfv

              # Распаковка и удаление архива
              tar -C ./ -xjf ~/uploads/logger-old-node.tar.bz2
              rm -rf ~/uploads/logger-old-node.tar.bz2

              # Установка правильной версии Node.js
              . ~/.nvm/nvm.sh
              nvm install lts/fermium
              nvm use lts/fermium

              # Установка зависимостей
              npm install

              # Создание папки для логов если не существует
              mkdir -p logs

              # Имя процесса из ecosystem.config.js
              APP_NAME="logger-old-node-backend"

              # Удаление старого процесса
              if pm2 list | grep -q $APP_NAME; then
                pm2 stop $APP_NAME
                pm2 delete $APP_NAME
              else
                echo "Process $APP_NAME not found, skipping..."
              fi

              # Запуск процесса
              pm2 start ecosystem.config.js --env production
              pm2 save
            echo "Error: Directory /var/www/${{ secrets.BACKEND_FOLDER }} does not exist!"
              exit 1
            fi
      - name: Success Notification
        uses: appleboy/telegram-action@master
        with:
          to: ${{ secrets.MN_TG_CHAT_ID }}
          token: ${{ secrets.TG_BOT_TOKEN }}
          format: markdown
          message: |
            *✅ Деплой успешно завершен*
            *🌍 Сервер:* Мечта
            *📱 Приложение:* «Logger Old Node»
            *🛠️ Тип:* Backend
            *Название коммита:* _${{ github.event.commits[0].message }}_

      - name: Failed Notification
        if: ${{ failure() }}
        uses: appleboy/telegram-action@master
        with:
          to: ${{ secrets.MN_TG_CHAT_ID }}
          token: ${{ secrets.TG_BOT_TOKEN }}
          format: markdown
          message: |
            *❌ Деплой завершен неудачей*
            *🌍 Сервер:* Мечта
            *📱 Приложение:* «Logger Old Node»
            *🛠️ Тип:* Backend
            *Название коммита:* _${{ github.event.commits[0].message }}_