name: Deploy to production server
on:
  push:
    branches:
      - master
    tags:
      - '**-prod**'

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest

    steps:
      - name: Start Notification
        uses: appleboy/telegram-action@master
        with:
          to: ${{ secrets.MN_TG_CHAT_ID }}
          token: ${{ secrets.TG_BOT_TOKEN }}
          format: markdown
          message: |
            *♻️ Деплой запущен*
            *🌍 Сервер:* Мечта
            *📱 Приложение:* «Logger Old Node»
            *🛠️ Тип:* Backend

      - name: Git clone repository
        uses: actions/checkout@v4

      - name: Create BZIP deployment package
        run: tar -cjf logger-old-node.tar.bz2 ./*

      - name: Copy file to serve
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          port: ${{ secrets.PORT }}
          source: logger-old-node.tar.bz2
          target: ~/uploads/

      - name: Deploy
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          port: ${{ secrets.PORT }}
          script: |
            TARGET_DIR="/var/www/${{ secrets.BACKEND_FOLDER }}"
            NVM_DIR="/usr/local/nvm"

            if [ ! -d "$TARGET_DIR" ]; then
              echo "::error::Critical: Target directory $TARGET_DIR does not exist!"
              exit 1
            fi

            cd $TARGET_DIR || exit 1

            # Удаляет все кроме папки node_modules
            ls | grep -v "node_modules" | xargs rm -rfv

            # Распаковка и удаление архива
            tar -C ./ -xjf ~/uploads/logger-old-node.tar.bz2
            rm -rf ~/uploads/logger-old-node.tar.bz2

            # Загрузка NVM (ваша конфигурация)
            export NVM_DIR="$NVM_DIR"
            [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"

            # Проверка что NVM загрузился
            if ! command -v nvm &> /dev/null; then
              echo "::error::NVM not loaded properly!"
              exit 1
            fi

            # Установка нужной версии Node.js
            nvm install lts/fermium
            nvm use lts/fermium

            # Проверка версии Node.js
            echo "Using Node.js version: $(node -v)"
            echo "Using npm version: $(npm -v)"

            # Установка зависимостей
            npm ci --no-audit --production

            # Проверяем существование папки и создаём если её нет
            [ -d "logs" ] || mkdir -p logs

            # Управление PM2 процессом
            APP_NAME="logger-old-node-backend"

            pm2 delete $APP_NAME 2>/dev/null || echo "No existing $APP_NAME process"
            pm2 start ecosystem.config.js --env production
            pm2 save

      - name: Success Notification
        uses: appleboy/telegram-action@master
        with:
          to: ${{ secrets.MN_TG_CHAT_ID }}
          token: ${{ secrets.TG_BOT_TOKEN }}
          format: markdown
          message: |
            *✅ Деплой успешно завершен*
            *🌍 Сервер:* Мечта
            *📱 Приложение:* «Logger Old Node»
            *🛠️ Тип:* Backend
            *Название коммита:* _${{ github.event.commits[0].message }}_

      - name: Failed Notification
        if: ${{ failure() }}
        uses: appleboy/telegram-action@master
        with:
          to: ${{ secrets.MN_TG_CHAT_ID }}
          token: ${{ secrets.TG_BOT_TOKEN }}
          format: markdown
          message: |
            *❌ Деплой завершен неудачей*
            *🌍 Сервер:* Мечта
            *📱 Приложение:* «Logger Old Node»
            *🛠️ Тип:* Backend
            *Название коммита:* _${{ github.event.commits[0].message }}_